# BrainX shared header — fetched from the canonical landing site and emitted
# as Sphinx static assets so the docs site shows the same brand header as
# https://brainx.chaobrain.com.
#
# Behavior (env vars):
#   BRAINX_HEADER_LOCAL=<dir>   read header.{html,css} from <dir> instead of
#                               fetching. Use this to live-preview against a
#                               local landing-site dist (e.g. ../brainx.chaobrain.com/dist/shared-header).
#   BRAINX_HEADER_OFFLINE=1     skip fetch, require cached copy. Build fails if
#                               cache is missing — never silently ships an empty
#                               header.
#   BRAINX_HEADER_TTL=<seconds> cache TTL, default 3600 (1h). Set to 0 to force
#                               refresh.
#   BRAINX_HEADER_URL=<url>     override base URL (default production).
#
# Cache lives at docs/_brand/ next to conf.py and is gitignored.

import json
import os
import time
from pathlib import Path
from urllib.request import Request, urlopen

DEFAULT_BASE = "https://brainx.chaobrain.com/shared-header"
DEFAULT_TTL  = 3600


def _read_local(local_dir: Path) -> tuple[str, str]:
    html = (local_dir / "header.html").read_text(encoding="utf-8")
    css  = (local_dir / "header.css").read_text(encoding="utf-8")
    return html, css


def _fetch(url: str, timeout: int = 10) -> str:
    req = Request(url, headers={"User-Agent": "brainx-docs-build"})
    with urlopen(req, timeout=timeout) as r:
        return r.read().decode("utf-8")


def _load_with_cache(base_url: str, cache_dir: Path, ttl: int, offline: bool) -> tuple[str, str]:
    cache_dir.mkdir(parents=True, exist_ok=True)
    html_path = cache_dir / "header.html"
    css_path  = cache_dir / "header.css"
    meta_path = cache_dir / "meta.json"

    fresh = False
    if meta_path.exists() and html_path.exists() and css_path.exists():
        try:
            meta = json.loads(meta_path.read_text())
            fresh = (time.time() - meta.get("ts", 0)) < ttl
        except Exception:
            fresh = False

    if not fresh and not offline:
        try:
            html = _fetch(f"{base_url}/header.html")
            css  = _fetch(f"{base_url}/header.css")
            html_path.write_text(html, encoding="utf-8")
            css_path.write_text(css,  encoding="utf-8")
            meta_path.write_text(json.dumps({"ts": time.time(), "src": base_url}))
            return html, css
        except Exception as e:
            if not html_path.exists():
                raise RuntimeError(
                    f"Failed to fetch BrainX header from {base_url} and no cache exists: {e}"
                ) from e
            print(f"[brainx-header] fetch failed ({e}); using stale cache from {html_path}")

    if not html_path.exists():
        raise RuntimeError(
            f"BRAINX_HEADER_OFFLINE=1 but no cache at {cache_dir}. "
            f"Run once online first, or unset OFFLINE."
        )
    return html_path.read_text(encoding="utf-8"), css_path.read_text(encoding="utf-8")


def install(docs_dir: Path) -> None:
    """Fetch (or read local) the BrainX header and emit Sphinx static assets.

    Writes:
      _static/css/brainx-header.css  — namespaced .bx-* styles + theme overrides
      _static/js/brainx-header.js    — DOM-ready injector that prepends the header

    Caller is responsible for adding these paths to html_css_files / html_js_files.
    """
    docs_dir  = Path(docs_dir)
    static    = docs_dir / "_static"
    css_out   = static / "css" / "brainx-header.css"
    js_out    = static / "js"  / "brainx-header.js"
    css_out.parent.mkdir(parents=True, exist_ok=True)
    js_out.parent.mkdir(parents=True, exist_ok=True)

    local = os.environ.get("BRAINX_HEADER_LOCAL")
    if local:
        html, css = _read_local(Path(local))
        print(f"[brainx-header] using local source: {local}")
    else:
        base    = os.environ.get("BRAINX_HEADER_URL", DEFAULT_BASE).rstrip("/")
        ttl     = int(os.environ.get("BRAINX_HEADER_TTL", DEFAULT_TTL))
        offline = os.environ.get("BRAINX_HEADER_OFFLINE") == "1"
        html, css = _load_with_cache(base, docs_dir / "_brand", ttl, offline)
        print(f"[brainx-header] source={base} offline={offline} ttl={ttl}")

    # Hide sphinx_book_theme's own top bars so the BrainX header is the only
    # visible header. The article header is generated by the theme and otherwise
    # overlaps the injected BrainX header.
    overrides = """

/* --- docs site overrides (not present on landing) --- */
header.bd-header,
.bd-header-article,
.header-article-items.header-article__inner {
  display: none !important;
}
body { padding-top: 0 !important; }
"""
    css_out.write_text(css + overrides, encoding="utf-8")

    # Inject HTML at top of <body> on DOM ready. Use JSON.stringify-safe encoding
    # by embedding via a JSON literal to avoid backtick / template issues.
    payload = json.dumps(html)
    js = f"""// Auto-generated by docs/_brainx_header.py from {os.environ.get('BRAINX_HEADER_URL', DEFAULT_BASE)}
(function () {{
  var HTML = {payload};
  function inject() {{
    if (document.querySelector('[data-bx-header]')) return;
    var holder = document.createElement('div');
    holder.innerHTML = HTML;
    var node = holder.firstElementChild;
    if (node) document.body.insertBefore(node, document.body.firstChild);
    if (!node) return;

    var burger = node.querySelector('[data-bx-burger]');
    if (!burger) return;
    burger.setAttribute('aria-label', 'Open documentation navigation');
    burger.addEventListener('click', function (event) {{
      var docsToggle = document.querySelector('.bd-header-article .primary-toggle');
      event.preventDefault();
      event.stopImmediatePropagation();
      if (docsToggle) {{
        docsToggle.click();
        return;
      }}
      var header = burger.closest('[data-bx-header]');
      if (header) header.classList.toggle('bx-open');
    }}, true);

    var themeToggle = node.querySelector('[data-bx-theme-toggle]');
    if (!themeToggle) return;
    themeToggle.addEventListener('click', function (event) {{
      var docsThemeToggle = document.querySelector('.bd-header-article .theme-switch-button');
      event.preventDefault();
      event.stopImmediatePropagation();
      if (docsThemeToggle) {{
        docsThemeToggle.click();
        return;
      }}
      document.documentElement.classList.toggle('dark');
    }}, true);
  }}
  if (document.readyState === 'loading') {{
    document.addEventListener('DOMContentLoaded', inject);
  }} else {{
    inject();
  }}
}})();
"""
    js_out.write_text(js, encoding="utf-8")
