name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

# Allow OIDC for trusted publishing while retaining token support
permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    # Only publish for final releases, or when triggered manually
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.release.prerelease == false)
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist and wheel (PEP 517)
        run: python -m build

      - name: Verify distributions metadata
        run: twine check dist/*

      - name: Upload built distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          # If your PyPI project is configured for Trusted Publishing,
          # the token is optional. This remains for backward compatibility.
          password: ${{ secrets.PYPI_API_TOKEN }}
